twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/horizontal_layout.html.twig'  # to be the default theme
